version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  config-server:
    image: $DOCKER_USERNAME/docker-repo:finance-service_config-server
    restart: always
    ports:
      - 8888:8080
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry-peer-1:
    image: $DOCKER_USERNAME/docker-repo:finance-service_registry-peer-1
    restart: always
    ports:
      - 8761:8080
    depends_on:
      - "config-server"
    command: >
        bash -c "./wait-for-it.sh config-server:8080 -t 180
        && java -Xmx200m -jar /app/registry-peer-1.jar"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry-peer-2:
    image: $DOCKER_USERNAME/docker-repo:finance-service_registry-peer-2
    restart: always
    ports:
      - 8762:8080
    depends_on:
      - "config-server"
    command: >
        bash -c "./wait-for-it.sh config-server:8080 -t 180
        && java -Xmx200m -jar /app/registry-peer-2.jar"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    image: $DOCKER_USERNAME/docker-repo:finance-service_gateway
    restart: always
    ports:
      - 4000:8080
    depends_on:
      - "config-server"
      - "registry-peer-1"
      - "registry-peer-2"
    command: >
        bash -c "./wait-for-it.sh config-server:8080 -t 180
        && ./wait-for-it.sh registry-peer-1:8080 -t 180
        && ./wait-for-it.sh registry-peer-2:8080 -t 180
        && java -Xmx200m -jar /app/gateway.jar"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  finance-service-mock-instance-1:
    image: $DOCKER_USERNAME/docker-repo:finance-service_finance-service-mock
    restart: always
    ports:
      - 5050:8080
    depends_on:
      - "config-server"
      - "registry-peer-1"
      - "registry-peer-2"
    command: >
        bash -c "./wait-for-it.sh config-server:8080 -t 180
        && ./wait-for-it.sh registry-peer-1:8080 -t 180
        && ./wait-for-it.sh registry-peer-2:8080 -t 180
        && java -Xmx200m -jar /app/finance-service-mock.jar"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  finance-service-mock-instance-2:
    image: $DOCKER_USERNAME/docker-repo:finance-service_finance-service-mock
    restart: always
    ports:
      - 5051:8080
    depends_on:
      - "config-server"
      - "registry-peer-1"
      - "registry-peer-2"
    command: >
        bash -c "./wait-for-it.sh config-server:8080 -t 180
        && ./wait-for-it.sh registry-peer-1:8080 -t 180
        && ./wait-for-it.sh registry-peer-2:8080 -t 180
        && java -Xmx200m -jar /app/finance-service-mock.jar"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  notification-service-mock:
    image: $DOCKER_USERNAME/docker-repo:finance-service_notification-service-mock
    restart: always
    ports:
      - 5055:8080
    depends_on:
      - "config-server"
      - "registry-peer-1"
      - "registry-peer-2"
    command: >
        bash -c "./wait-for-it.sh config-server:8080 -t 180
        && ./wait-for-it.sh registry-peer-1:8080 -t 180
        && ./wait-for-it.sh registry-peer-2:8080 -t 180
        && java -Xmx200m -jar /app/notification-service-mock.jar"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  monitoring:
    image: $DOCKER_USERNAME/docker-repo:finance-service_monitoring
    restart: always
    ports:
      - 9000:8080
      - 8989:8989
    depends_on:
      - "config-server"
      - "registry-peer-1"
      - "registry-peer-2"
    command: >
        bash -c "./wait-for-it.sh config-server:8080 -t 180
        && ./wait-for-it.sh registry-peer-1:8080 -t 180
        && ./wait-for-it.sh registry-peer-2:8080 -t 180
        && java -Xmx200m -jar /app/monitoring.jar"
    logging:
      options:
        max-size: "10m"
        max-file: "10"