services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  config-server:
    image: $DOCKER_USERNAME/docker-repo:finance-service_config-server
    restart: always
    ports:
      - "8888:8888"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    image: $DOCKER_USERNAME/docker-repo:finance-service_registry
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"