version: '2.1'
services:
  rabbitmq:
    ports:
      - 15672:15672

  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry

  gateway:
    build: gateway

  finance-service-mock:
    build: finance-service
    ports:
      - 5050:5050

  notification-service-mock:
    build: notification-service
    ports:
      - 6000:6000

  monitoring:
    build: monitoring