spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/services
  profiles:
     active: native

server:
  port: 8888
  context-path: /config-server

security:
  user:
    password: ${CONFIG_SERVER_PASSWORD}