# External configuration for Finance Service

server:
  port: 5050
  context-path: /finance-service

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    statusPageUrlPath: ${server.context-path}/health
    healthCheckUrlPath: ${server.context-path}/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://registry-peer-1:8761/registry/eureka, http://registry-peer-2:8762/registry/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

spring:
  rabbitmq:
    host: rabbitmq