# External configuration for Gateway

server:
  port: 4000
  context-path: /gateway

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    ipAddress: 127.0.0.1
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://registry:8761/registry/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    finance-service:
        path: /finance-service/**
        serviceId: finance-service-mock
        stripPrefix: false
        sensitiveHeaders:

    notification-service:
        path: /notification-service/**
        serviceId: notification-service-mock
        stripPrefix: false
        sensitiveHeaders: