#External configuration for Monitoring

server:
  port: 9000
  context-path: /monitoring

turbine:
  stream:
    port: 8989
# TODO find why cluster name doesn't affect on monitored service in Turbine
#  aggregator:
#    clusterConfig: GATEWAY
# appConfig: gateway

logging:
  level:
    com:
      netflix: DEBUG