# External configuration for Monitoring

server:
  port: 9000
  context-path: /monitoring

turbine:
  stream:
    port: 8989

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    ipAddress: 127.0.0.1
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://registry-peer-1:8761/registry/eureka, http://registry-peer-2:8762/registry/eureka

spring:
  rabbitmq:
    host: rabbitmq