#External configuration for Finance Service

server:
  port: 6000
  context-path: /notification-service

eureka:
  instance:
    hostname: localhost
    port: 8761
    prefer-ip-address: true
    ipAddress: 127.0.0.1
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: ${server.context-path}/info
    healthCheckUrl: ${server.context-path}/health
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/registry/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000