# External configuration for Notification Service

server:
  context-path: /notification-service

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://registry-peer-2:8080/registry/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

spring:
  rabbitmq:
    host: rabbitmq