# External configuration for Service Registry

server:
  port: 8762
  context-path: /registry

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    ipAddress: 127.0.0.1
  server:
    enable-self-preservation: false
    waitTimeInMsWhenSyncEmpty: 0
  client:
    serviceUrl:
      defaultZone: http://registry-peer-1:8761/registry/eureka/